[build]
  # Configuration for the build process

[compile]
  # Configuration for the compilation process
  optimizer = true
  runs = 200
  evmVersion = "petersburg"

[contracts]
  # Paths to where contracts are stored
  directory = "./contracts"

[networks]
  # Configuration for the development network
  [networks.development]
  host = "127.0.0.1"
  port = 7545
  network_id = "*"

  # Configuration for the Rinkeby test network
  [networks.rinkeby]
  network_id = 4
  provider = "https://rinkeby.infura.io/v3/${INFURA_API_KEY}"
  gas = 7000000
  gasPrice = 20000000000 # 20 Gwei

[plugins]
  # List of Truffle plugins

[mocha]
  # Mocha test framework configuration
  enableTimeouts = false
  before_timeout = 120000 # 2 minutes before each test suite
